{% set name = "dedupe-variable-datetime" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dedupe-variable-datetime-{{ version }}.tar.gz
  sha256: 3af618c39471b046e634db5f0c4aae9e92d65217f03c5cdfc0657e6f7a42c416

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - datetime-distance
    - future
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - dedupe.variables

about:
  home: https://github.com/datamade/dedupe-variable-datetime
  summary: DateTime variable type for dedupe
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
    - izahn
